# Set here your webhook url
discordUrl: https://discord.com/api/webhooks/your_webhook_link

# If link was send to the command executor
# true | false
serverMessage: true

# If logs will be sending when the server stop
# true | false
sendLogOnStop: true

# Optional | add here a message to send in the discord in addition to the link
discordMessage: Hi, look latest logs of my server.


