name: DiscordLogs
version: '${project.version}'
main: nardann.discordlogs.DiscordLogs
api-version: '${project.bukkitAPIVersion}'
commands:
  discordlogs:
    description: Sends logs to Discord
    permission: discordlogs.logs
  discordlogsreload:
    description: Sends a message to Discord
    permission: discordlogs.reload
